name: Daily Random README Commits

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # keep GITHUB_TOKEN for pushing

      - name: Set commit identity to YOU
        run: |
          git config user.name "arjunwritescode"
          git config user.email "arjunveersinghrathore17@gmail.com"  # <-- replace with your exact noreply or verified email

      - name: Make 1–5 tiny commits
        run: |
          n=$(( (RANDOM % 5) + 1 ))
          echo "Will make $n commits"
          for i in $(seq 1 $n); do
            echo "<!-- noise-$i $(date +%s) -->" >> auto_commit_log.txt

            # Stage and commit with explicit author (belt & suspenders)
            git add auto_commit_log.txt
            git commit \
              --author="Arjun Rathore <arjunveersinghrathore17@gmail.com>" \
              -m "🤖 Auto noise commit #$i"

            # Push to the default branch
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:main
            sleep 2
          done
